[package]
name = "sa-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
metaheuristics = "1.1.22"
rand = "0.8.5"
sim = { "path" = "../sim" }
time = "0.3.30"
